label: Services
type: structure
modalsize: large
entry: >
  Type: {{type}}<br />
  <strong>{{headline}}</strong><br />
  <br />
  {{description}}
  Preis: {{price}} €<br />
fields:
  type:
    label: Type
    type: select
    options:
      Express: Express
      Vor-Ort: Vor-Ort
      Kurierdienst: Kurier
      Per-Post: Per Post
      Stationar: Stationäre Aufnahme
  headline: headline
  description: description
  button_text: button_text
